
package com.auth.server.api.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AuthorizeImplService", targetNamespace = "http://impl.api.server.auth.com/", wsdlLocation = "http://127.0.0.1:8090/Authorize?wsdl")
public class AuthorizeImplService
    extends Service
{

    private final static URL AUTHORIZEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException AUTHORIZEIMPLSERVICE_EXCEPTION;
    private final static QName AUTHORIZEIMPLSERVICE_QNAME = new QName("http://impl.api.server.auth.com/", "AuthorizeImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8090/Authorize?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUTHORIZEIMPLSERVICE_WSDL_LOCATION = url;
        AUTHORIZEIMPLSERVICE_EXCEPTION = e;
    }

    public AuthorizeImplService() {
        super(__getWsdlLocation(), AUTHORIZEIMPLSERVICE_QNAME);
    }

    public AuthorizeImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTHORIZEIMPLSERVICE_QNAME, features);
    }

    public AuthorizeImplService(URL wsdlLocation) {
        super(wsdlLocation, AUTHORIZEIMPLSERVICE_QNAME);
    }

    public AuthorizeImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTHORIZEIMPLSERVICE_QNAME, features);
    }

    public AuthorizeImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthorizeImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AuthorizeImpl
     */
    @WebEndpoint(name = "AuthorizeImplPort")
    public AuthorizeImpl getAuthorizeImplPort() {
        return super.getPort(new QName("http://impl.api.server.auth.com/", "AuthorizeImplPort"), AuthorizeImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuthorizeImpl
     */
    @WebEndpoint(name = "AuthorizeImplPort")
    public AuthorizeImpl getAuthorizeImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.api.server.auth.com/", "AuthorizeImplPort"), AuthorizeImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTHORIZEIMPLSERVICE_EXCEPTION!= null) {
            throw AUTHORIZEIMPLSERVICE_EXCEPTION;
        }
        return AUTHORIZEIMPLSERVICE_WSDL_LOCATION;
    }

}
