
package com.auth.server.api.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AuthorizeImpl", targetNamespace = "http://impl.api.server.auth.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AuthorizeImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createRole", targetNamespace = "http://impl.api.server.auth.com/", className = "com.auth.server.api.impl.CreateRole")
    @ResponseWrapper(localName = "createRoleResponse", targetNamespace = "http://impl.api.server.auth.com/", className = "com.auth.server.api.impl.CreateRoleResponse")
    @Action(input = "http://impl.api.server.auth.com/AuthorizeImpl/createRoleRequest", output = "http://impl.api.server.auth.com/AuthorizeImpl/createRoleResponse")
    public String createRole(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "inValidate", targetNamespace = "http://impl.api.server.auth.com/", className = "com.auth.server.api.impl.InValidate")
    @ResponseWrapper(localName = "inValidateResponse", targetNamespace = "http://impl.api.server.auth.com/", className = "com.auth.server.api.impl.InValidateResponse")
    @Action(input = "http://impl.api.server.auth.com/AuthorizeImpl/inValidateRequest", output = "http://impl.api.server.auth.com/AuthorizeImpl/inValidateResponse")
    public void inValidate(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authenticate", targetNamespace = "http://impl.api.server.auth.com/", className = "com.auth.server.api.impl.Authenticate")
    @ResponseWrapper(localName = "authenticateResponse", targetNamespace = "http://impl.api.server.auth.com/", className = "com.auth.server.api.impl.AuthenticateResponse")
    @Action(input = "http://impl.api.server.auth.com/AuthorizeImpl/authenticateRequest", output = "http://impl.api.server.auth.com/AuthorizeImpl/authenticateResponse")
    public String authenticate(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createUser", targetNamespace = "http://impl.api.server.auth.com/", className = "com.auth.server.api.impl.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://impl.api.server.auth.com/", className = "com.auth.server.api.impl.CreateUserResponse")
    @Action(input = "http://impl.api.server.auth.com/AuthorizeImpl/createUserRequest", output = "http://impl.api.server.auth.com/AuthorizeImpl/createUserResponse")
    public String createUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteRole", targetNamespace = "http://impl.api.server.auth.com/", className = "com.auth.server.api.impl.DeleteRole")
    @ResponseWrapper(localName = "deleteRoleResponse", targetNamespace = "http://impl.api.server.auth.com/", className = "com.auth.server.api.impl.DeleteRoleResponse")
    @Action(input = "http://impl.api.server.auth.com/AuthorizeImpl/deleteRoleRequest", output = "http://impl.api.server.auth.com/AuthorizeImpl/deleteRoleResponse")
    public String deleteRole(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteUser", targetNamespace = "http://impl.api.server.auth.com/", className = "com.auth.server.api.impl.DeleteUser")
    @ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://impl.api.server.auth.com/", className = "com.auth.server.api.impl.DeleteUserResponse")
    @Action(input = "http://impl.api.server.auth.com/AuthorizeImpl/deleteUserRequest", output = "http://impl.api.server.auth.com/AuthorizeImpl/deleteUserResponse")
    public String deleteUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addRoleToUser", targetNamespace = "http://impl.api.server.auth.com/", className = "com.auth.server.api.impl.AddRoleToUser")
    @ResponseWrapper(localName = "addRoleToUserResponse", targetNamespace = "http://impl.api.server.auth.com/", className = "com.auth.server.api.impl.AddRoleToUserResponse")
    @Action(input = "http://impl.api.server.auth.com/AuthorizeImpl/addRoleToUserRequest", output = "http://impl.api.server.auth.com/AuthorizeImpl/addRoleToUserResponse")
    public String addRoleToUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "allRoles", targetNamespace = "http://impl.api.server.auth.com/", className = "com.auth.server.api.impl.AllRoles")
    @ResponseWrapper(localName = "allRolesResponse", targetNamespace = "http://impl.api.server.auth.com/", className = "com.auth.server.api.impl.AllRolesResponse")
    @Action(input = "http://impl.api.server.auth.com/AuthorizeImpl/allRolesRequest", output = "http://impl.api.server.auth.com/AuthorizeImpl/allRolesResponse")
    public String allRoles(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkRole", targetNamespace = "http://impl.api.server.auth.com/", className = "com.auth.server.api.impl.CheckRole")
    @ResponseWrapper(localName = "checkRoleResponse", targetNamespace = "http://impl.api.server.auth.com/", className = "com.auth.server.api.impl.CheckRoleResponse")
    @Action(input = "http://impl.api.server.auth.com/AuthorizeImpl/checkRoleRequest", output = "http://impl.api.server.auth.com/AuthorizeImpl/checkRoleResponse")
    public String checkRole(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
